WIP: add biometrics login
ZeusLN/zeus pull request #1301
Opened 2023-02-05 15:41 UTC by channelninja

# Description

Relates to issue: **ZEUS-1108**

This is a WIP since I can't test it on a real device.

This pull request is categorized as a:

- [x] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance 
- [ ] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [ ] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [ ] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [ ] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [ ] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [ ] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] Core Lightning (Spark)
- [ ] Eclair
- [ ] LndHub

### Locales
- [x] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the Zeus [Transfix page](https://www.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [x] Contributors will need to run `yarn` after this PR is merged in
- [x] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

2023-02-05 15:47 UTC, kaloudis commented on package.json
> +    "react-native-biometrics": "^3.0.1",
we like to lock version numbers. remove the `^` and run yarn again

2023-02-05 15:50 UTC, channelninja commented on package.json
> +    "react-native-biometrics": "^3.0.1",
changed

2023-02-05 22:34 UTC, kaloudis commented on views/Settings/Security.tsx
> +                            }}
call `updateSettings({ isBiometryEnabled: !isBiometryEnabled })` here

2023-02-05 22:34 UTC, kaloudis commented on views/Settings/Security.tsx
> +    }
no need for these two functions. just call `updateSettings` in the Switch `onValueChange`

2023-02-05 22:43 UTC, kaloudis commented on locales/en.json
> +    "views.Lockscreen.TouchID.prompt": "Unlock Zeus",
please try to not reuse values. no need for a translator to translate the same string 2 times

2023-02-06 09:52 UTC, channelninja commented
Somehow my comments got added multiple times to different conversations 🤷

2023-02-06 18:02 UTC, channelninja commented
https://github.com/SelfLender/react-native-biometrics/issues/240
Could someone with a samsung or huawei device check if FaceId works?

2023-02-12 00:03 UTC, kaloudis requested changes

2023-02-12 00:03 UTC, kaloudis commented on ios/zeus/Info.plist
> +	<string>Text explains why you need the FaceID</string>
We need to fill this out with a proper description

2023-02-12 00:04 UTC, kaloudis commented on views/Lockscreen.tsx
> +            settings.supportedBiometryType !== undefined &&
I think the `!== undefined` here is redundant

2023-02-12 00:04 UTC, kaloudis commented on views/Lockscreen.tsx
> +                return;
is this `return` here required?

2023-02-12 23:51 UTC, Talej commented
A couple of places use: 

`settings.isBiometryEnabled && settings.supportedBiometryType !== undefined`

Could be a bit cleaner to turn that into a utility helper function.

Checks out over here on iPhone 11 iOS 16.2

2023-02-13 14:52 UTC, channelninja commented
@Talej changed it.

2023-02-14 01:41 UTC, kaloudis approved these changes
tACK. Great first contribution!

2023-02-14 01:42 UTC, merged