Improve expiry display
ZeusLN/zeus pull request #1534
Opened 2023-07-02 19:57 UTC by myxmaster

# Description

Instead of displaying the initially defined time until expiration, the remaining time is now displayed in a human readable form. Also made the layout more consistent by putting labels on the left and values on the right.

![grafik](https://github.com/ZeusLN/zeus/assets/77545287/dbd1f451-4446-4221-94cd-aad2b6377b9b)

![grafik](https://github.com/ZeusLN/zeus/assets/77545287/96ec5503-01ec-4c05-b8e1-6368be8c2261)

Before:

![grafik](https://github.com/ZeusLN/zeus/assets/77545287/c94bc340-4ee0-4f68-8e26-1a3e7659e91c)

![grafik](https://github.com/ZeusLN/zeus/assets/77545287/e4775332-701a-414d-a961-4b41f9176bf8)

This fixes #1509.

This pull request is categorized as a:

- [ ] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance 
- [x] Other

## Checklist
- [x] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [x] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] Core Lightning (Spark)
- [ ] Eclair
- [ ] LndHub

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the Zeus [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [x] Contributors will need to run `yarn` after this PR is merged in
- [x] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

2023-08-02 09:31 UTC, shubhamkmr04 reviewed
utACK

2023-08-03 15:00 UTC, shubhamkmr04 requested changes
![Screenshot 2023-08-03 at 8 29 20 PM](https://github.com/ZeusLN/zeus/assets/50761978/6c27e899-5ee3-4b7b-87d2-ef5c30cffcce)
We are getting expiration time as 0 seconds in LNDHub. I am using Alby instance in this one

2023-08-04 20:51 UTC, kaloudis commented
> ![Screenshot 2023-08-03 at 8 29 20 PM](https://user-images.githubusercontent.com/50761978/258152405-6c27e899-5ee3-4b7b-87d2-ef5c30cffcce.png) We are getting expiration time as 0 seconds in LNDHub. I am using Alby instance in this one

Yeah, as suspected we need to test this against all the backends

2023-08-14 20:54 UTC, myxmaster commented
@shubhamkmr04 Kind of fixing this blindly, please check if it's working now.

2023-09-06 17:00 UTC, kaloudis commented
@myxmaster can you fix the conflicts here?

This PR will pave the way for this to work with LNDHub and all the other backends https://github.com/ZeusLN/zeus/pull/1652

2023-10-01 19:28 UTC, kaloudis commented
Instead of saying `4 days, 2 hours` and it refers to the time to expiration and not the absolute time it is valid for, perhaps it should say `4 days, 2 hours from now`

2023-10-25 02:24 UTC, kaloudis commented
@myxmaster what's the raw formatting of that timestamp above?

2023-11-18 18:10 UTC, kaloudis commented on utils/Bolt11Utils.ts
> +// based on light-bolt11-decoder: Copyright (c) 2021 bitcoinjs contributors, fiatjaf
what enhancements have been made here that make it faster than the original library?

2023-12-22 16:10 UTC, kaloudis commented
Looking good, tested on LND and CLN so far.

Do we need to display expiry on paid invoices?

2023-12-22 16:22 UTC, kaloudis commented
<img width="446" alt="Screenshot 2023-12-22 at 11 21 44" src="https://github.com/ZeusLN/zeus/assets/1878621/2ebcdd75-77b6-45a1-bf3f-87173ec99fef">

Furthermore, on an expired request, maybe we remove the third line and replace the title with 'Expired request' or 'Expired invoice'?

2023-12-22 18:13 UTC, shubhamkmr04 commented
Tested for LND and LNDHub in both iOS and Android. Working fine.

2023-12-30 17:00 UTC, kaloudis approved these changes
tACK

2023-12-30 17:00 UTC, merged