CONTACTS
ZeusLN/zeus pull request #1618
Opened 2023-08-23 17:32 UTC by shubhamkmr04

2023-09-05 03:06 UTC, kaloudis requested changes

2023-09-05 03:06 UTC, kaloudis commented on views/Settings/AddContacts.tsx
> +            <KeyboardAvoidingView
This view should be wrapped with the `Screen` component to give it the proper background

2023-09-05 03:06 UTC, kaloudis commented on views/Settings/AddContacts.tsx
> +                    backgroundColor: themeColor('background')
background color here should be transparent

2023-09-05 03:06 UTC, kaloudis commented on views/Settings/AddContacts.tsx
> +                        backgroundColor={themeColor('background')}
background color here should be transparent

2023-09-05 03:06 UTC, kaloudis commented on views/Settings/AddContacts.tsx
> +                                {dropdownValues.map((value, index) => (
let's define the maps in this file with `(value: any, index: number)` at a bare minimum

2023-09-05 03:08 UTC, kaloudis commented on views/Send.tsx
> +                                        navigation.navigate(
instead of navigating back to contacts when the chip is closed, the destination and contact name should be cleared from the state.

If the user wants to choose a different contact instead, they can hit the contact book icon at the end of the field

2023-09-05 03:08 UTC, kaloudis commented on views/Send.tsx
> +                                    // hideConversion={amount === 'all'}
why is this commented out?

2023-09-05 03:10 UTC, kaloudis commented on locales/en.json
> +    "views.Settings.ContactsSettings.contacts": "CONTACTS",
for these two in all caps, let's keep the casing standard and then make them all caps with JS: `.toUpperCase()`

2023-09-05 03:10 UTC, kaloudis commented on utils/AddressUtils.test.ts
> +    });
great job adding the tests here

2023-09-05 03:13 UTC, kaloudis commented on views/Settings/ContactsSettings.tsx
> +                    : contact[field].includes(search);
need to modify this slightly so it is case insensitive: perhaps `.toLowerCase()` can be appended to both the `contact[field]` and `search` to get this to work?

2023-09-05 03:19 UTC, kaloudis commented
The `react-native-elements` `SearchBar` components doesn't have an option to turn autocapitalization off. Can we use the `TextInput` component instead somehow?

2023-09-05 15:46 UTC, shubhamkmr04 commented on views/Send.tsx
> +                                    // hideConversion={amount === 'all'}
Can't recall when I changed it. I'll just undo it

2023-09-07 21:50 UTC, kaloudis commented on .github/PULL_REQUEST_TEMPLATE.md
> -- [ ] Changes were made that require an update to onboarding
why'd this file get changed?

2023-09-07 21:50 UTC, kaloudis commented
nit: change `AddContacts.tsx` -> `AddContact.tsx`

2023-09-07 21:52 UTC, kaloudis commented
is `ContactSettings` more accurately called `Contacts` or `ContactList`?

2023-09-08 14:20 UTC, shubhamkmr04 commented on .github/PULL_REQUEST_TEMPLATE.md
> -- [ ] Changes were made that require an update to onboarding
Maybe when I fixed some conflicts, I ran prettier so it is changed

2023-09-08 14:21 UTC, shubhamkmr04 commented
> is `ContactSettings` more accurately named `Contacts` or `ContactList`?

Maybe `Contacts` would be better

2023-09-08 16:15 UTC, kaloudis commented on .github/PULL_REQUEST_TEMPLATE.md
> -- [ ] Changes were made that require an update to onboarding
Please undo the change

2023-09-08 16:33 UTC, kaloudis commented on ios/zeus.xcodeproj/project.pbxproj
> +}
this file shouldn't change

2023-09-08 16:33 UTC, kaloudis commented on locales/en.json
> +    "views.Settings.Contacts.noContacts": "No Contacts",
this file shouldn't remove the LSP strings

2023-09-08 16:33 UTC, kaloudis commented on views/Settings/AddContact.tsx
> +        const AddPhotos = () => (
nit: space before this line

2023-09-08 16:34 UTC, kaloudis commented on views/Settings/Settings.tsx
> +                                        Contacts
this should be a locale string

2023-09-08 16:35 UTC, kaloudis commented on views/Settings/AddContact.tsx
> +                                                if (text === '') {
I think `!text` will work here as well

2023-09-08 16:37 UTC, kaloudis commented on views/Settings/Contacts.tsx
> +                                ({favoriteContacts.length})
let's format this with custom function string formatting

`${localeString('views.Settings.Contacts.favorites').toUpperCase() (${favoriteContacts.length})`

2023-09-08 16:37 UTC, kaloudis commented on views/Settings/Contacts.tsx
> +                                ({nonFavoriteContacts.length})
same here

2023-09-08 16:38 UTC, kaloudis commented on utils/LinkingUtils.ts
> +        if (url.startsWith('nostr:')) {
why not add `nostr:` handling to `handleAnything`?

2023-09-11 08:40 UTC, shubhamkmr04 commented on locales/en.json
> +    "views.Settings.Contacts.noContacts": "No Contacts",
Ahh. didn't see that, might have removed them by mistake

2023-09-11 09:15 UTC, shubhamkmr04 commented on views/Settings/Contacts.tsx
> +                                ({favoriteContacts.length})
Giving me syntax error on this one

2023-09-13 00:07 UTC, kaloudis commented
Let's add Nostr deeplinking functionality to NIP-05s too

2023-09-15 16:26 UTC, kaloudis requested changes

2023-09-15 16:26 UTC, kaloudis commented on views/ContactDetails.tsx
> +                            {contact.pubkey.length >= 1 &&
on all these checks we also need to see if `contact.x` exists. otherwise, things will break if/when we add new fields to the contacts

2023-09-18 19:17 UTC, kaloudis commented
tACK

2023-09-18 19:17 UTC, kaloudis approved these changes

2023-09-18 19:17 UTC, merged