Currency Converter
ZeusLN/zeus pull request #1968
Opened 2024-02-01 14:03 UTC by shubhamkmr04

2024-02-01 17:04 UTC, kaloudis commented
`CurrencyConverter` not `CurrencyConvertor`

2024-02-02 15:27 UTC, kaloudis commented on views/Settings/CurrencyConverter.tsx
> +                                title="Select Currency"
needs localization

2024-02-02 15:27 UTC, kaloudis commented on views/Settings/CurrencyConverter.tsx
> +                                    placeholder={`Enter amount in ${currency}`}
needs localization

2024-02-07 18:53 UTC, kaloudis commented on views/Settings/CurrencyConverter.tsx
> +                    placeholder={`Enter amount in ${currency}`}
needs to be localized. Although here maybe we should show the currency flag as well

2024-02-07 18:53 UTC, kaloudis commented on views/Settings/CurrencyConverter.tsx
> +                                                placeholder={`Enter amount in ${item}`}
localize

2024-02-13 15:54 UTC, kaloudis commented on views/Settings/AddCurrencies.tsx
> +import * as React from 'react';
Do we really need this file or can we add in the functionality to `SelectCurrency`?

2024-02-13 16:28 UTC, shubhamkmr04 commented on views/Settings/AddCurrencies.tsx
> +import * as React from 'react';
Hmm, I'll figure out if we can

2024-02-15 15:28 UTC, shubhamkmr04 commented on views/Settings/AddCurrencies.tsx
> +import * as React from 'react';
I have added this functionality in `SelectCurrency` and removed `AddCurrencies`

2024-02-19 02:19 UTC, kaloudis commented on assets/images/SVG/bitcoin-icon.svg
are we using this file anymore?

2024-02-19 02:22 UTC, kaloudis commented
I'm hitting some edge cases where I forms are unresponsive when I add them at first, sometimes. Also issues with the order not getting saved, after reordering fields.

2024-02-19 12:39 UTC, shubhamkmr04 commented on assets/images/SVG/bitcoin-icon.svg
Not right now, but I am thinking of using it in placeholder for BTC and SAT inputs.

2024-02-19 15:17 UTC, kaloudis commented on assets/images/SVG/bitcoin-icon.svg
Let's add it then

2024-02-19 15:22 UTC, kaloudis commented
reordering is fixed now - but still having an issue with new fields not affecting the others

2024-02-19 16:59 UTC, kaloudis commented
Perhaps the country flag should  always be displayed and be to the right of the currency code on the right side

2024-02-19 17:30 UTC, shubhamkmr04 commented
> Perhaps the country flag should always be displayed and be to the right of the currency code on the right side

got it

2024-02-19 17:34 UTC, shubhamkmr04 commented
> reordering is fixed now - but still having an issue with new fields not affecting the others

I didn't quite understand that bug.

2024-02-20 14:25 UTC, kaloudis commented on views/Settings/CurrencyConverter.tsx
> +                let convertedValue = '';
why the change from a number to a string here?

2024-02-21 12:05 UTC, shubhamkmr04 commented on views/Settings/CurrencyConverter.tsx
> +                let convertedValue = '';
revamped this function according to type string, its better this way also because we are using `numberWithDecimals` and `numberWithCommas` now. Working perfectly now with applying the formatting to the currencies.

2024-02-22 19:13 UTC, kaloudis requested changes

2024-02-22 19:13 UTC, kaloudis commented on assets/images/SVG/bitcoin-icon.svg
Please remove this if we're not using it

2024-02-27 16:12 UTC, kaloudis approved these changes

2024-02-27 16:12 UTC, merged