Custom pictures for node config
ZeusLN/zeus pull request #2010
Opened 2024-02-29 09:38 UTC by shubhamkmr04

2024-03-07 04:33 UTC, kaloudis commented on views/Settings/NodeConfiguration.tsx
> +        console.log(node);
remove log

2024-03-07 04:34 UTC, kaloudis commented on views/Settings/NodeConfiguration.tsx
> +            photo
photo not used here

2024-03-07 04:34 UTC, kaloudis commented on views/Settings/SelectNodeProfile.tsx
> +                    title="Upload picture"
localize this

2024-03-07 04:36 UTC, kaloudis commented on views/Settings/NodeConfiguration.tsx
> +        updateSettings({ node: updatedNode });
unsure why you needs these lines here

2024-03-14 21:11 UTC, kaloudis commented
We have some conflicts

2024-03-14 21:11 UTC, kaloudis commented
I think we can go smaller with the image sizes. Should probably still look good at a quarter of the size I think

2024-03-15 09:04 UTC, shubhamkmr04 commented
> I think we can go smaller with the image sizes. Should probably still look good at a quarter of the size I think

Reduced it by 30%, we'll have to compromise the quality if we shrink the size more than this

2024-03-15 14:07 UTC, kaloudis requested changes

2024-03-15 14:07 UTC, kaloudis commented on views/Settings/SetNodePicture.tsx
> +                require('../../assets/images/LND.jpg')
I want these last four to be programmatically set, depending on which backend is being used

2024-03-18 11:14 UTC, shubhamkmr04 commented on views/Settings/SetNodePicture.tsx
> +                require('../../assets/images/LND.jpg')
Done.

2024-03-19 02:38 UTC, kaloudis requested changes
When you change the node picture, it doesn't change the state on the `NodeConfiguration` page as not saved, like it would be if you changed one of the fields.

Other than that I think it's looking good

2024-03-19 14:33 UTC, shubhamkmr04 commented
> When you change the node picture, it doesn't change the state on the `NodeConfiguration` page as not saved, like it would be if you changed one of the fields.
> 
> Other than that I think it's looking good

I think we are changing state after coming to `NodeConfiguration` view in `InitProps` function line **327** and **343**

2024-03-19 18:18 UTC, kaloudis commented on views/Settings/SetNodePicture.tsx
> +                        });
here we should also set `saved: false` to update the state

2024-03-19 18:18 UTC, kaloudis commented on views/Settings/NodeConfiguration.tsx
> +                                              this.setState(
here we should set `saved: false` since the photo is changing

2024-03-20 14:48 UTC, kaloudis commented on views/Settings/NodeConfiguration.tsx
> +                                        node?.photo === null) &&
could you simply do `!node.photo` in place of `node?.photo === '' || node?.photo === null`?

2024-03-26 09:46 UTC, shubhamkmr04 commented
> Nice PR! A few ideas/general feedback:
> 
> 1. This should be fixed (happens when list of default images are displayed):
>    `VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.`
> 2. When you pick an image and click button "SET PICTURE", it is not really set, because you still need to click on next button "SAVE NODE CONFIG". I think it should be all done after clicking the first button (set picture). (Or if you don't like that idea, maybe rename "SET PICTURE" to "CHOOSE PICTURE", because you are not really setting it here.)
> 3. When an image for a node was already set, then you go to settings again and click on that image, it is removed and the "+" icon is displayed (and the explainer "For now, the Embedded LND nodes cannot be deleted..." is gone!). I would expect to be able to just pick another image, when I click on it.
> 4. When an image is already set, it is not exactly intuitive that you can actually click on the node image in node settings to change it. This is especially problematic in case Zeus picks images automatically when configuring a new node in the future (e.g. LND image for LND nodes). I think many users will not be aware they can change it. Not sure how to solve this nicely, but I guess we need some kind of "Edit node image" label.
> 5. When there is PIN/passphrase configured and you pick an image from gallery, Zeus will ask for PIN/passphrase when you are back in Zeus and after logging in you are back in default view -> you cannot set the node image.
> 6. I think it is a lot of Zeus images, maybe there should be categories which users can expand/collapse.

Thanks for the detailed feedback! After a discussion with @kaloudis, I have updated the name to 'Choose Picture'. We will address the remaining points outlined in the feedback through subsequent PRs.

2024-03-26 16:50 UTC, kaloudis commented
>     5. When there is PIN/passphrase configured and you pick an image from gallery, Zeus will ask for PIN/passphrase when you are back in Zeus and after logging in you are back in default view -> you cannot set the node image.

Related issue here https://github.com/ZeusLN/zeus/issues/1880

2024-03-26 22:59 UTC, kaloudis commented
>     4. When an image is already set, it is not exactly intuitive that you can actually click on the node image in node settings to change it. This is especially problematic in case Zeus picks images automatically when configuring a new node in the future (e.g. LND image for LND nodes). I think many users will not be aware they can change it. Not sure how to solve this nicely, but I guess we need some kind of "Edit node image" label.

I was thinking a red circle and `-` in the top right corner of the image to remove it, but it would likely be too small. Might need to pull in a designer for this one

2024-03-26 23:00 UTC, kaloudis approved these changes

2024-03-26 23:00 UTC, merged