Refactor error handling to display more user friendly errors
ZeusLN/zeus pull request #2052
Opened 2024-03-12 15:28 UTC by shubhamkmr04

# Description

Relates to issue: **[ZEUS-2003](https://github.com/ZeusLN/zeus/issues/2003)**

_Please enter a description and screenshots, if appropriate, of the work covered in this PR_

This pull request is categorized as a:

- [ ] New feature
- [X] Bug fix
- [X] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance
- [ ] Other

## Checklist
- [X] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [X] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [X] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [ ] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [X] No, I’m a fool
- [ ] Yes
- [ ] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [X] Android
- [X] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] Embedded LND
- [X] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] LndHub
- [ ] [DEPRECATED] Core Lightning (Spark)
- [ ] [DEPRECATED] Eclair

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the ZEUS [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

2024-03-14 15:46 UTC, kaloudis commented on utils/ErrorUtils.ts
>  const errorToUserFriendly = (error: string, localize = true) => {
love this approach of extending this function

2024-03-14 15:47 UTC, kaloudis commented on utils/ErrorUtils.test.ts
> +            );
good tests here but you should add cases where message is on `errorObject.error.message`

2024-03-17 23:38 UTC, kaloudis requested changes

2024-03-17 23:38 UTC, kaloudis commented on stores/ChannelsStore.ts
> +                                error.message.toString()
why do we have to pick message off the object and convert to string here?

We should be able to pass in the error raw and have the function handle the rest, ie. `errorToUserFriendly(error)`

2024-03-19 17:31 UTC, shubhamkmr04 commented on stores/ChannelsStore.ts
> +                                error.message.toString()
Made the changes accordingly.

2024-03-19 18:23 UTC, kaloudis commented on utils/ErrorUtils.ts
> +const errorToUserFriendly = (error: any, localize = true) => {
this is still incorrect. Type should be of `:Error` not `:any`

2024-03-19 18:25 UTC, kaloudis commented on stores/ChannelsStore.ts
>              .catch((error: any) => {
change the type here and on line 501 to `Error`

2024-03-19 18:25 UTC, kaloudis commented on stores/InvoicesStore.ts
>              .catch((error: any) => {
change the type here to `Error`

2024-03-20 06:01 UTC, kaloudis commented on utils/ErrorUtils.ts
> +    if (typeof error === 'object') {
shouldn't type always be `Error` now?

2024-03-20 06:02 UTC, kaloudis commented on utils/ErrorUtils.ts
> +        }
I don't think this block should be returning the message as is. We should probably try to see if we can localize it after we parse the error string out of the object

2024-03-20 06:04 UTC, kaloudis commented on utils/ErrorUtils.test.ts
> +                })
I thought we would have had to wrap the inputs w/ Error constructors here. Interesting that it all still passes.

2024-03-22 05:42 UTC, kaloudis commented on utils/ErrorUtils.ts
> +    let errorMessage: object | string | any = error.message;
this is getting much closer but not quite, right.

Shouldn't this always be a `string`? The case in which it's an object is not covered in the test cases. The test cases should also include actual `Error` objects being passed in

2024-03-26 08:21 UTC, shubhamkmr04 commented on utils/ErrorUtils.ts
> +    let errorMessage: object | string | any = error.message;
Yes, you are right, error.message is always string  in all cases. Also added `Error` objects in test cases in the recent commit

2024-03-26 22:11 UTC, kaloudis approved these changes
LGTM

2024-03-26 22:11 UTC, merged