Wiring up Endpoints
ZeusLN/zeus pull request #2097
Opened 2024-03-28 12:25 UTC by shubhamkmr04

2024-05-04 03:44 UTC, kaloudis commented on stores/LSPStore.ts
> +            this.error_msg = 'Did not receive response from server';
this needs to be localized

2024-05-04 03:46 UTC, kaloudis commented on views/Settings/LSPS1/Order.tsx
> +                                            value={result.channel_expiry_blocks}
let's format this with commas

2024-05-04 03:46 UTC, kaloudis commented on views/Settings/LSPS1/Order.tsx
> +                                                    : 'False'
let's localize these - we have them defined already in our locales

2024-05-04 03:47 UTC, kaloudis commented on views/Settings/LSPS1/OrdersPane.tsx
> +                                text: `LSPS1 Orders (${orders.length})`,
let's localize this

2024-05-08 15:03 UTC, kaloudis commented on views/Settings/LSPS1/Order.tsx
> +                                    message={`${LSPStore.error_msg}: Showing Previous State`}
localization needed here. Please fix the casing to `showing previous state`

2024-05-08 15:04 UTC, kaloudis requested changes

2024-05-08 15:04 UTC, kaloudis commented on views/Settings/LSPS1/Order.tsx
> +            '03e84a109cd70e57864274932fc87c5e6434c59ebb8e6e7d28532219ba38f7f6df@139.144.22.237:9735';
this being hard-coded is problematic, we should be able to pull the peer info from the existing order data so that we know which peer to query.

If we leave it as is, this is going to break if you are not using the default LSP peer all the time.

2024-05-09 08:54 UTC, shubhamkmr04 commented
[e3f389](https://github.com/ZeusLN/zeus/pull/2097/commits/e3f389e5a4482d2a084824f591f673ee2a776da1):
- Localize string
- Show error if no orders are stored yet
- Fix warning `Each child in a list should have a unique key prop` on **OrdersPane** view
- Format Channel expiry block input with commas

2024-05-13 14:05 UTC, kaloudis commented on views/Settings/LSPS1/index.tsx
> +                    // );
remove this if we're not using it

2024-05-13 14:07 UTC, kaloudis commented on stores/LSPStore.ts
> +        const endpoint = `${peerOrEndpoint}/api/v1/get_order?order_id=${id}`;
why the var name `peerOrEndpoint`? it's always going to be a REST endpoint on this call every time

2024-05-13 14:08 UTC, kaloudis commented on views/Settings/LSPS1/Order.tsx
> +                            : this.lsps1_getorder(id, peerOrEndpoint);
do we need `lsps1_getorder` in the view? can we move it to the store?

2024-05-13 14:09 UTC, kaloudis commented on views/Settings/LSPS1/Order.tsx
> +                            temporaryOrder.peer || temporaryOrder.endpoint;
don't think we need to make this variable if we're checking whether REST is supported or not on the line below

2024-05-13 18:05 UTC, kaloudis commented on stores/LSPStore.ts
> +    public lsps1_getorder(orderId: string, peer: string) {
rename to `getOrderCustomMessage`

2024-05-13 18:07 UTC, shubhamkmr04 commented on views/Settings/LSPS1/Order.tsx
> +                            : this.lsps1_getorder(id, peerOrEndpoint);
Yes that would be good. Did the change

2024-05-23 02:09 UTC, kaloudis commented on views/Settings/LSPS1/OrdersPane.tsx
> +                    const orders = selectedOrders.map((response) => ({
I think we can clean this block up a bit by checking if `result` exists on the object and defining the order depending on it.

Something like

```
const order = response?.order?.result || response?.order;

return {
        orderId: order.order_id,
        state: order.order_state,
        createdAt: order.created_at,
        fundedAt: order.funded_at,
        lspBalanceSat: order.lsp_balance_sat
}
```

2024-05-24 04:40 UTC, kaloudis approved these changes

2024-05-24 04:40 UTC, merged