Node Pictures: Save images location directly and remove 'handleImageTap'
ZeusLN/zeus pull request #2100
Opened 2024-03-30 08:20 UTC by shubhamkmr04

2024-03-30 17:29 UTC, kaloudis commented on views/Settings/SetNodePicture.tsx
> +    getPhoto(photo: string | null): object | string {
Why was it necessary to change the structure of the `getPhoto` calls? Seems like we could have just removed `handleImageTap` and made the change on line 194

2024-03-30 18:07 UTC, kaloudis commented
This approach doesn't work. Images are lost on reload

2024-03-31 10:24 UTC, shubhamkmr04 commented on views/Settings/SetNodePicture.tsx
> +    getPhoto(photo: string | null): object | string {
We did that coz we needed the object to return with the key `uri` to fetch gallery imported photos

2024-03-31 10:32 UTC, shubhamkmr04 commented
> What if we refactor `handleImageTap` to just save the image uri?
> 
> ```
> handleImageTap = async (item) => {
>         try {
>             // Fetch the local image
>             const imageUri = Image.resolveAssetSource(item).uri;
>             this.setState({ photo: imageUri });
>         } catch (error) {
>             console.error('Error resolving image uri:', error);
>         }
>     };
> ```

yup we can do that

2024-03-31 18:28 UTC, kaloudis commented
Holds up against Android upgrades. About to test iOS

2024-03-31 18:46 UTC, kaloudis requested changes
Does not hold up on iOS, I believe the file paths change every upgrade.

We'll have to emulate what we do on custom images and save a copy of the image that we point to.

2024-04-01 18:18 UTC, kaloudis commented
The file storage is working correctly now, however the approach isn't quite right.

We are unnecessarily creating new copies of each image every time we tap it. The 'download' event should only trigger once the `Choose Picture` button is pressed

2024-04-02 16:17 UTC, kaloudis approved these changes
passing all my tests. nice work

2024-04-02 16:17 UTC, merged