POS: Add Delete Product btn and remove the icon
ZeusLN/zeus pull request #2205
Opened 2024-05-24 10:45 UTC by shubhamkmr04

https://github.com/ZeusLN/zeus/issues/2199

2024-05-24 16:01 UTC, kaloudis commented
@shubhamkmr04 can you provide before and after screenshots?

2024-05-24 16:39 UTC, shubhamkmr04 commented
> @shubhamkmr04 can you provide before and after screenshots?

Yes, updated the description!

2024-05-24 21:09 UTC, kaloudis requested changes

2024-05-24 21:09 UTC, kaloudis commented on views/POS/ProductDetails.tsx
> +                                                if (!this.state.confirmDelete) {
nit: since we're referencing `this.state.confirmDelete` twice, let's destructure it on 227

2024-05-26 07:09 UTC, shubhamkmr04 commented on views/POS/ProductDetails.tsx
> +                                                if (!this.state.confirmDelete) {
updated.

2024-05-26 16:13 UTC, kaloudis approved these changes

2024-05-26 16:13 UTC, merged