New-cln-rest-api
ZeusLN/zeus pull request #2228
Opened 2024-06-08 22:29 UTC by niteshbalusu11

# Description

Relates to issue: #1637

Depracates c-lightning-rest and adds a new backend using core-lightning team maintained CLN Rest.
Important Note: Minimum core-lightning version to use this is `v24.02` due to breaking changes from cln team.
This PR should cover all features which the old backend was covering.
I have not tested this on iOS coz I wasn't able to get xcode to build zeus.

This pull request is categorized as a:

- [X] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance
- [ ] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [X] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [X] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [X] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [ ] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [X] Android
- [ ] iOS

2024-06-10 00:27 UTC, kaloudis commented on backends/CLightningREST.ts
thanks for the fixes here!

2024-06-10 00:27 UTC, kaloudis commented on backends/CoreLightningRestApi.ts
nit: let's rename this file and class `CLNRest`

2024-06-10 00:27 UTC, kaloudis commented on backends/CoreLightningRestApi.ts
We can leave the name of the request handler file as is, as we might use it with other CLN interfaces

2024-06-10 00:29 UTC, kaloudis commented on stores/SettingsStore.ts
> +    { key: 'Core Lightning REST API', value: 'core-lightning-rest-api' },
nit: let's call the key `Core Lightning (CLNRest)` and the value `cln-rest`

2024-06-10 03:28 UTC, niteshbalusu11 commented
Fixed and rebased

2024-06-10 14:25 UTC, vincenzopalazzo requested changes
Ok looks like that you arrive before me, I left some comments because in this way I can build on top of you

2024-06-10 14:25 UTC, vincenzopalazzo commented on backends/CLNRest.ts
> +export default class CLNRest extends LND {
```suggestion
export default class CLNRest  {
```

There is no reason to extend LND, but we should re-export the method `getUrl` somewhere-else

2024-06-10 15:20 UTC, niteshbalusu11 commented on backends/CLNRest.ts
> +        this.supports('v0.8.2', undefined, 'v0.4.0');
These are old functions that existed in the previous c-lightning-rest and i copied them over. Probably will leave them as is.

2024-06-10 15:20 UTC, niteshbalusu11 commented on views/Settings/NodeConfiguration.tsx
> +                        {implementation === 'cln-rest' && (
Because cln-rest uses runes and the old one uses a macaroon. We can just delete the old when Zeus wants to depracate it completely. Right now both are supported.

2024-06-10 15:21 UTC, niteshbalusu11 commented on backends/CLNRest.ts
> +export default class CLNRest extends LND {
Some views are breaking when we not extend from lnd, also all the actual execution of the fetch calls happen in the LND class so its not just getUrl. Will leave it as is.

2024-06-10 15:22 UTC, kaloudis commented on backends/CLNRest.ts
> +        this.supports('v0.8.2', undefined, 'v0.4.0');
I think you may have to delete the third parameter as that is an API version check

2024-06-10 15:23 UTC, vincenzopalazzo commented on views/Settings/NodeConfiguration.tsx
> +                        {implementation === 'cln-rest' && (
>Because cln-rest uses runes and the old one uses a macaroon.  

are the same things a the concept level, you can just replace the string with `implementation === 'cln-rest' ? "rune" : "macaroon"` no?

2024-06-10 15:23 UTC, vincenzopalazzo commented on backends/CLNRest.ts
> +        this.supports('v0.8.2', undefined, 'v0.4.0');
can you clarify at least what `v0.8.2` is?

2024-06-10 15:25 UTC, niteshbalusu11 commented on backends/CLNRest.ts
> +        this.supports('v0.8.2', undefined, 'v0.4.0');
Maybe we just mark it as true since its being supported from a very old version and the new cln-rest we are only supporting from v24.0.2 anyway?

2024-06-10 15:27 UTC, vincenzopalazzo commented on backends/CLNRest.ts
> +export default class CLNRest extends LND {
>also all the actual execution of the fetch calls happen in the LND class so its not just getUrl. 

What do you mean? This approach will leave many calls unused, and you'll likely need to rewrite a lot of code as well when you support commando (or you are not supporting it?).

TL;DR: I disagree with using CLN code that relies on LND. Even though the current API design is different, the previous design wasn't bad because c-lightning-REST emulates LND. However, clnrest/commando does not.

2024-06-10 15:32 UTC, niteshbalusu11 commented on views/Settings/NodeConfiguration.tsx
> +                        {implementation === 'cln-rest' && (
I just find them cleaner to be separate because old c-lightning-rest is sharing with now anyway. Whatever Evan wants.

2024-06-10 15:35 UTC, niteshbalusu11 commented on backends/CLNRest.ts
> +export default class CLNRest extends LND {
We are not supporting Commando in this PR. 
The only thing the CLN class relies on LND is the actual "fetch" function to call the APIs. everything else is separate. I tried removing the LND class extension but that was breaking a couple of UI components. I didn't find the time to investigate that.

2024-06-10 15:57 UTC, niteshbalusu11 commented on backends/CLNRest.ts
> +export default class CLNRest extends LND {
Nvm, i figured out the issue. CLN no longer extends LND now.

2024-06-10 20:17 UTC, sha-265 commented
you are too fast 😵‍💫 

anyway, this is probably a good opportunity to fix `getTransactions()` which uses wrong API method ('listtransactions`), as i did in my version:
https://github.com/sha-265/zeus/blob/c40d9c1ba20c504f5e3355cf33d9e8b4409fca09/backends/CLNRest.ts#L33

2024-06-10 22:07 UTC, niteshbalusu11 commented
> anyway, this is probably a good opportunity to fix `getTransactions()` that uses wrong api method (`listfunds` which return the wallet utxos, and not transactions history), as i did in my version: https://github.com/sha-265/zeus/blob/c40d9c1ba20c504f5e3355cf33d9e8b4409fca09/backends/CLNRest.ts#L33

Thank you for catching that. I think your code is missing tag == `channel_open` and tag == `channel_close` which idk if cln also records has deposit and withdrawal. also it records chain_fee separately. 
Have to look into that.

2024-06-11 03:08 UTC, newtonick commented
I get this error when trying send onchain in signet via CLNRest (via this PR)

"unknown parameter: address, this may be caused by
a failure to autodetect key=value-style parameters.
Please try using the -k flag and explicit key=value
pairs of parameters."

![image](https://github.com/ZeusLN/zeus/assets/127377/cab4725e-82b4-4fde-8db7-f8da40d90403)
![image](https://github.com/ZeusLN/zeus/assets/127377/7837af64-2625-4514-b415-db536ea4c2f7)

2024-06-11 03:18 UTC, newtonick commented on backends/CLNRest.ts
> +                address: data.addr,
should address be destination? https://docs.corelightning.org/reference/lightning-withdraw

2024-06-11 13:56 UTC, niteshbalusu11 commented on backends/CLNRest.ts
> +                address: data.addr,
Thank you for catching that. fixed.

2024-06-11 14:15 UTC, newtonick commented on backends/CLNRest.ts
> +                feeRate: `${Number(data.sat_per_vbyte) * 1000}perkb`,
`feeRate` should also be `feerate` and `satoshis` should also be `satoshi`. Sorry I didn't catch that when I saw address was wrong.

2024-06-11 14:18 UTC, niteshbalusu11 commented on backends/CLNRest.ts
> +                feeRate: `${Number(data.sat_per_vbyte) * 1000}perkb`,
No, not your fault. I missed them. I fixed them now.

2024-06-11 14:28 UTC, sha-265 commented
> > anyway, this is probably a good opportunity to fix `getTransactions()` that uses wrong api method (`listfunds` which return the wallet utxos, and not transactions history), as i did in my version: https://github.com/sha-265/zeus/blob/c40d9c1ba20c504f5e3355cf33d9e8b4409fca09/backends/CLNRest.ts#L33
> 
> Thank you for catching that. I think your code is missing tag == `channel_open` and tag == `channel_close` which idk if cln also records has deposit and withdrawal. also it records chain_fee separately. Have to look into that.

i don't see this tags (at least under `wallet` account), but there is a `journal_entry` tag that should be filtered out maybe.

2024-06-11 14:44 UTC, sha-265 commented
> > i don't see this tags (at least under `wallet` account), but there is a `journal_entry` tag that should be filtered out maybe.
> 
> Yeah, that's the problem, it doesn't put it under wallet. Have to figure out where it does. In the examples in the docs, it puts it under some long string account. Have to see what that is.

it's channel id according to the cln documentation:
> account (string): The account name. If the account is a channel, the channel_id.

i'm not sure this events are relevant if you want only the on-chain transactions.

2024-06-11 15:14 UTC, niteshbalusu11 commented
> i'm not sure these events are relevant if you want only the on-chain transactions.

I think they are relevant because channel opens and closes are chain txs. I pushed a commit to include those. Please test if you can. I just pushed a commit to make the txs more readable so you know what the tx is for with a new notes field.

2024-06-11 15:24 UTC, sha-265 commented
> > i'm not sure these events are relevant if you want only the on-chain transactions.
> 
> I think they are relevant because channel opens and closes are chain txs. I pushed a commit to include those. Please test if you can. I just pushed a commit to make the txs more readable so you know what the tx is for with a new notes field.

i don't know if there is no duplicate events in `wallet` account for channel opening (at least). 

but i think in terms of performance query with out `account` parameters would be much more heavy as it returns all the non on-chain events, that could be a lot of events, so it should be considered also.

2024-06-11 15:35 UTC, niteshbalusu11 commented
> but i think in terms of performance query without account parameter, would be much more heavy as it returns all the non on-chain events

I agree. CLNs APIs don't seem to allow pagination as well which is annoying. Maybe someone can test with their mainnet node which is old and see how it performs. 
They should ideally have a simple RPC for chain txs but I'm not gonna rant about their RPC build choices here.

2024-06-11 15:45 UTC, sha-265 commented
> > but i think in terms of performance query without account parameter, would be much more heavy as it returns all the non on-chain events
> 
> I agree. CLNs APIs don't seem to allow pagination as well which is annoying. Maybe someone can test with their mainnet node which is old and see how it performs. They should ideally have a simple RPC for chain txs but I'm not gonna rant about their RPC build choices here.

yep, not the best api i've come across 🤷‍♂️

other solution could be somehow to make only one query for `getTransactions()` and `getInvoices()` instead of two separated calls for the same data.

2024-06-13 21:01 UTC, newtonick commented
From what testing I have been able to do, I believe activity view needs some love. It might be helpful to start with what transactions should be included in this view. I'm not sure if this is documented somewhere (like a previous zeus GitHub issue/PR/etc). What I expect to be listed in the activity view is:

- lightning Invoices (paid, unpaid, expired)
- lightning payment (successful payments only) w/ fees
- onchain withdraw/payment (in mempool and onchain) w/ fees
- onchain receives (in mempool and onchain)

I don't expect to see channel open / close transactions but I also don't mind if they are in this view if it's communicated that they are part of an open/close channel transaction.

Right now I see multiple rows in the activity view for a single on chain payments. I have a hard time dissecting what information bkpr-listaccountevents is returning. Sorry this comment is not more helpful. I just wanted to provide feedback on what I have tested so far with this PR. Thank you for this work.

2024-06-13 21:09 UTC, niteshbalusu11 commented
> What I expect to be listed in the activity view is:

lightning Invoices (paid, unpaid, expired)
lightning payment (successful payments only) w/ fees
onchain withdraw/payment (in mempool and onchain) w/ fees
onchain receives (in mempool and onchain)

This sounds good to me except expired and unpaid invoices, that could be a bit too much specially expired. 
I will leave it to @kaloudis once he tests and gives feedback on what he thinks.

2024-06-13 21:12 UTC, newtonick commented
Here is an example of 40,000 sat onchain spend (https://mutinynet.com/tx/99a918361919956cc76801b6014e233d834466dbb25b4f031825e1eb60b972e8) that shows 3 rows in the activity view for a single spend transaction. The 40,000 sat row appears first as soon as I complete the spend (while the tx is in the mempool). This shows as a credit but is actually a debit. Then once the transaction is confirmed into 1+ blocks, 2 more rows appear. A debit of the utxo I used to make the spend and then a credit of the change back to my wallet.

![image](https://github.com/ZeusLN/zeus/assets/127377/95597a0b-ccf1-4602-85b7-fb2653f421d2)

2024-06-13 21:16 UTC, niteshbalusu11 commented
> Here is an example of 40,000 sat onchain spend (https://mutinynet.com/tx/99a918361919956cc76801b6014e233d834466dbb25b4f031825e1eb60b972e8) that shows 3 rows in the activity view for a single spend transaction. The 40,000 sat row appears first as soon as I complete the spend (while the tx is in the mempool). This shows as a credit but is actually a debit. Then once the transaction is confirmed into 1+ blocks, 2 more rows appear. A debit of the utxo I used to make the spend and then a credit of the change back to my wallet.
> 
> ![image](https://github.com/ZeusLN/zeus/assets/127377/95597a0b-ccf1-4602-85b7-fb2653f421d2)
> 

Ok, yeah this needs to be fixed. Only the spend should show up, not the utxos spent and change received.

2024-06-13 21:24 UTC, sha-265 commented
> I don't expect to see channel open / close transactions but I also don't mind if they are in this view if it's communicated that they are part of an open/close channel transaction.

i agree, and it's also solve the potential performance issue, as you can request only `wallet` account events, and not all the events for all the accounts in this node.

2024-06-14 00:07 UTC, niteshbalusu11 commented
ok @newtonick can you test now? I think it should be fixed.

@sha-265 unfortunately i think we can't get around the performance issue without compromising accuracy of the info because CLN displays change outputs as deposits and its really difficult to figure out if its a real deposit or a change output from like channel opens without checking channel opens from events. I asked in the CLN group if there is an easy way to check if an address is ours in CLN so that we can easily filter out change, let's see.

2024-06-14 00:53 UTC, sha-265 commented
i don't understand how tons of irrelevant events solving this, but at least you should get the same data only once and not three different times.

2024-06-14 00:55 UTC, niteshbalusu11 commented
> i don't understand how tons of irrelevant events solving this, but at least you should get the same data only once and not three different times.

I don't understand what you mean? I am getting only once.

2024-06-14 01:03 UTC, sha-265 commented
look here:
https://github.com/ZeusLN/zeus/blob/e89187c68c6de95487ce94267849e1c1b416e9c5/stores/ActivityStore.ts#L165-L168

i think if you are using `bkpr-listaccountevents` this three calls are overlapping.

2024-06-14 01:05 UTC, niteshbalusu11 commented
> look here:
> https://github.com/ZeusLN/zeus/blob/e89187c68c6de95487ce94267849e1c1b416e9c5/stores/ActivityStore.ts#L165-L168
> 
> i think if you are using `bkpr-listaccountevents` this three calls are overlapping.

Ah, that's old code. I never touched that. Will look into it.

2024-06-15 21:49 UTC, niteshbalusu11 commented
Ok I was right. It is what it is with CLN. 

![Screenshot_20240615-174835.png](https://github.com/ZeusLN/zeus/assets/84944042/2d75a6d2-e039-4999-b0b4-10c596717402)

2024-06-16 00:49 UTC, niteshbalusu11 commented
https://github.com/ElementsProject/lightning/issues/7397

2024-06-26 06:36 UTC, Sjors commented
I finally got the clnrest plugin to work (Python environments are a pain...). Happy to test all this when there's a testflight build.

2024-07-05 15:43 UTC, kaloudis requested changes

2024-07-05 15:43 UTC, kaloudis commented on backends/CLightningREST.ts
> -            encodingtype: 'hex'
can we revert this change? this will break connections for people with existing configurations

2024-07-09 15:03 UTC, kaloudis approved these changes
tACK

All things looking good. Congrats, @niteshbalusu11 you will be receiving the bounty.

We are expecting you to help address any issues that may arise during alpha and beta testing - not expecting anything major as we've already done some extensive testing

2024-07-09 15:04 UTC, merged

2024-07-15 16:30 UTC, Sjors commented
Just tested the https://github.com/ZeusLN/zeus/releases/tag/v0.9.0-beta1 release on iOs. It manages to connect!

I can seen my utxos on the coins screen. I can see my channels.

I can create an invoice to receive. The screen doesn't update when the invoice is paid, but afaik it didn't do that with c-lightning-rest either.

The Activity tab still crashes as it did with c-lightning-rest.

The combination of the above two things means I can't see if a payment to me succeeded.

I can pay a regular bolt11 invoice.

2024-07-15 16:42 UTC, niteshbalusu11 commented
> The Activity tab still crashes as it did with c-lightning-rest.

@Sjors is your node really old with a lot of data?

2024-07-15 16:48 UTC, Sjors commented
@niteshbalusu11 the node is very old, but it does run the latest v24.05. It has tens of 10K+ transactions, mostly keysends from podcasting 2.0 listeners.

I guess it's tripping over missing field in older transactions?

2024-07-15 17:27 UTC, niteshbalusu11 commented
> I guess it's tripping over missing field in older transactions?

It could also be that the response from the 10k+ txns could be very large because the RPC call right now has no way limit the records returned. Working on figuring that part out.

2024-07-16 00:09 UTC, niteshbalusu11 commented
This *might* fix some issues.

https://github.com/ZeusLN/zeus/pull/2290

2024-09-01 20:32 UTC, sha-265 commented
> Important Note: Minimum core-lightning version to use this is `v24.02` due to breaking changes from cln team.

I don't know how, but it's working for me with older version

2024-09-02 06:34 UTC, Sjors commented
> The screen doesn't update when the invoice is paid, but afaik it didn't do that with c-lightning-rest either.

More recently this usually does work.

> The Activity tab still crashes as it did with c-lightning-rest.

This is fixed since.