New screen: On-chain addresses
ZeusLN/zeus pull request #2242
Opened 2024-06-15 13:25 UTC by myxmaster

# Description

This adds "On-chain addresses" to the menu:

![grafik](https://github.com/ZeusLN/zeus/assets/77545287/b36f8d22-994a-4b79-9422-a84953f84cf9)

This displays all addresses from LND's [ListAddresses](https://lightning.engineering/api-docs/api/lnd/wallet-kit/list-addresses/index.html) grouped by account and address type. Allows hiding 0-balance addresses and sorting by creation time and balance.

![grafik](https://github.com/ZeusLN/zeus/assets/77545287/1ad3e2a3-3e29-4a27-9a33-6679a771f928)

This pull request is categorized as a:

- [x] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance
- [ ] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [x] Embedded LND
- [x] LND (REST)
- [x] LND (Lightning Node Connect)
- [ ] Core Lightning (c-lightning-REST)
- [ ] LndHub
- [ ] [DEPRECATED] Core Lightning (Spark)
- [ ] [DEPRECATED] Eclair

### Locales
- [x] I’ve added new locale text that requires translations
- [x] I’m aware that new translations should be made on the ZEUS [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [x] Contributors will need to run `yarn` after this PR is merged in
- [x] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

2024-08-28 02:47 UTC, kaloudis commented
We gotta change the icon. Currently it's credit cards?

2024-09-18 15:08 UTC, kaloudis commented
![Simulator Screenshot - iPhone 15 Pro Max - 2024-09-18 at 11 07 30](https://github.com/user-attachments/assets/2a9eca0f-2ed8-4a00-9de3-6d34cfebafd2)

Dropdown values not displaying correctly on iOS

2024-09-18 15:13 UTC, kaloudis commented on views/OnChainAddresses.tsx
> +                            key: s,
should be `key: localeString(`views.OnChainAddresses.sortBy.${s}`),`

2024-09-18 15:14 UTC, kaloudis commented
We need to configure this for Lightning Node Connect and Embedded LND as well

2024-09-18 15:15 UTC, kaloudis commented
This view should also probably just replace the current `Coins` view

2024-09-18 15:15 UTC, kaloudis commented
Lastly, we should think about adding the ability for users to pick the account they want to generate addresses for

2024-09-18 15:15 UTC, kaloudis requested changes
see comments above

2024-09-18 15:26 UTC, kaloudis commented
I think the sections should be collapsible (perhaps by default) - that way users will be able to navigate more easily if they have a ton of addresses

2024-09-22 02:30 UTC, kaloudis commented on backends/LND.ts
> +    supportsAddressesWithDerivationPaths = () => this.supports('v0.18.0');
since other backend utils are derived from LND, we're going to have to explicitly mark them as `false`

2024-09-22 02:47 UTC, kaloudis commented on views/OnChainAddresses.tsx
> +        const listAddressesResponse = await BackendUtils.listAddresses();
we should probably move this call to the `UTXOsStore`

2024-09-22 02:48 UTC, kaloudis commented on views/OnChainAddresses.tsx
> +        const listAddressesResponse = await BackendUtils.listAddresses();
Also, I think this is problematic. Fetching all addresses at once can lead to timeouts on nodes that have a bunch generated. Instead, I think it would be better to fetch the accounts list and then fetch the addresses for each account, one at a time.

We'd have to refactor quite a bit, but I don't think things will hold up as is.

2024-09-22 02:50 UTC, kaloudis commented
> This view should also probably just replace the current `Coins` view

after giving some thought to this, I think if `supportsAddressesWithDerivationPaths` - then we should show this new view, otherwise show the old view.

In keeping in sync with the Coins button under the On-chain balance slider, we should label the button on the Menu view `Coins` as well, and use the same icon.

2024-09-25 02:01 UTC, kaloudis commented
Tons of changes wired up:

- All three LND interfaces wired up
- Error handling for timed out `ListAddresses` call
- Ability to collapse address groups
- Ability to generate addresses for each address group
- Address count added to each address group header
- Menu icon reverted to Coins icon

![simulator_screenshot_03769D24-6D89-499E-B6C1-003361D6CCC4](https://github.com/user-attachments/assets/1266d9f1-2492-4987-a040-76bcd05cb9d9)

2024-09-26 09:31 UTC, shubhamkmr04 commented on views/OnChainAddresses.tsx
> +                            onRefresh={() => this.loadAddresses()}
I can't find where have we defined `loadAddresses`

2024-09-26 11:34 UTC, shubhamkmr04 reviewed
https://github.com/user-attachments/assets/b04e7e4d-91fb-4531-9d72-a5f30a050d24

I think hide 0-balance should not remove the complete view in case we only have o-balance addresses

2024-09-26 11:41 UTC, shubhamkmr04 reviewed
https://github.com/user-attachments/assets/cf43b42c-b270-4b4a-bc09-dbbffab00dba

the view glitch when we tap to add

2024-09-26 16:02 UTC, kaloudis commented
> Simulator.Screen.Recording.-.iPhone.15.Pro.-.2024-09-26.at.17.10.42.mp4
> 
> the view glitch when we tap to add

I think we need a separate issue for this. Mind filing one?

2024-09-27 14:15 UTC, shubhamkmr04 reviewed
![Simulator Screenshot - iPhone 15 Pro Max - 2024-09-27 at 19 43 53](https://github.com/user-attachments/assets/be0f26cb-7910-40b9-a728-1a568ab0d13c)
should we have one option here to generate in case we have no addresses?

2024-09-27 14:29 UTC, shubhamkmr04 commented
> > Simulator.Screen.Recording.-.iPhone.15.Pro.-.2024-09-26.at.17.10.42.mp4
> > the view glitch when we tap to add
> 
> I think we need a separate issue for this. Mind filing one?

we can track the issue here https://github.com/ZeusLN/zeus/issues/2441

2024-09-27 14:36 UTC, kaloudis commented
> ![Simulator Screenshot - iPhone 15 Pro Max - 2024-09-27 at 19 43 53](https://private-user-images.githubusercontent.com/50761978/371566411-be0f26cb-7910-40b9-a728-1a568ab0d13c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDc5OTEsIm5iZiI6MTcyNzQ0NzY5MSwicGF0aCI6Ii81MDc2MTk3OC8zNzE1NjY0MTEtYmUwZjI2Y2ItNzkxMC00MGI5LWE3MjgtMWE1NjhhYjBkMTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDE0MzQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZGNjZWEwZmE5MjQyMzFhZDkzZGVmZTRjYjZiY2JjMWU2ZjA4ZDNhNjE5ZjMxODlkOWIwNTk0ODgwY2Y0MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BhCafgpqfGNWGui7CfMiOe1dvxtShnZTw-ie6EVPoJ8) should we have one option here to generate in case we have no addresses?

![simulator_screenshot_11D196C3-D77B-4195-8F2C-1302CDF87A4C](https://github.com/user-attachments/assets/1d5ad0d5-ec5c-43e5-881f-209f0681728c)

Create button now added to the corner when no addresses have been generated yet

2024-09-27 14:41 UTC, shubhamkmr04 reviewed
tACK

2024-09-27 14:45 UTC, merged