New feature : Csv Export
ZeusLN/zeus pull request #2273
Opened 2024-07-01 09:38 UTC by Ajeett01

# Description

Relates to issue: **ZEUS-#1467**

2024-07-08 08:46 UTC, shubhamkmr04 commented on package.json
> +    "@json2csv/plainjs": "^7.0.6",
Lock the version here (remove `^` and run yarn `again`)

2024-07-08 08:46 UTC, shubhamkmr04 commented on package.json
> +    "@babel/plugin-transform-export-namespace-from": "^7.24.7",
here too

2024-07-08 08:49 UTC, shubhamkmr04 commented
We might have to change the file name from `JsonToCsv.tsx` to something else. 
@kaloudis your thoughts?

2024-07-08 08:52 UTC, kaloudis commented on views/Activity/JsonToCsv.tsx
> +                        <Button title="Download CSV" onPress={downloadCsv} />
this needs to be locatlized

2024-07-08 08:52 UTC, kaloudis commented
> We might have to change the file name from `JsonToCsv.tsx` to something else. @kaloudis your thoughts?

`ActivityToCsv`, perhaps?

2024-07-08 08:55 UTC, shubhamkmr04 commented on views/Activity/JsonToCsv.tsx
> +                        <Button title="Download CSV" onPress={downloadCsv} />
@Ajeett01 look through [locale files](https://github.com/ZeusLN/zeus/blob/master/locales/en.json) and add your used strings here

2024-07-08 08:58 UTC, shubhamkmr04 commented
> > We might have to change the file name from `JsonToCsv.tsx` to something else. @kaloudis your thoughts?
> 
> `ActivityToCsv`, perhaps?

Yup we can, or maybe `ImportActivity`, lets iterate on that

2024-07-08 08:59 UTC, shubhamkmr04 commented on views/Activity/Activity.tsx
> +                    size={30}
adjust the download icon size here as compared to filter and cross icons

2024-07-08 09:15 UTC, shubhamkmr04 commented on babel.config.js
> +    ]
why have we added that?

2024-07-08 09:16 UTC, shubhamkmr04 commented on views/Activity/JsonToCsv.tsx
> +        ];
@kaloudis would these keys be good to download in our csv data?

2024-07-08 14:16 UTC, kaloudis commented on views/Activity/JsonToCsv.tsx
> +        ];
these look ok, definitely need to flesh them out though

2024-08-07 15:58 UTC, kaloudis commented on views/Activity/ActivityToCsv.tsx
> +                    buttonPositive: 'OK'
We should localize these strings

2024-08-08 14:17 UTC, shubhamkmr04 commented
@Ajeett01 We need to fix failing check on the latest commit

2024-09-10 19:04 UTC, kaloudis requested changes

2024-09-10 19:04 UTC, kaloudis commented on views/Activity/ActivityToCsv.tsx
> +                return `Transaction Section\n${header}\n${rows}`;
this should be localized

2024-09-10 19:04 UTC, kaloudis commented on views/Activity/ActivityToCsv.tsx
> +                ].join(',');
these should be localized

2024-09-10 19:04 UTC, kaloudis commented on views/Activity/ActivityToCsv.tsx
> +                    'Invoice Section',
this needs localization

2024-09-10 19:04 UTC, kaloudis commented on views/Activity/ActivityToCsv.tsx
> +                    'Payment Section',
this needs localization

2024-09-10 19:04 UTC, kaloudis commented on views/Activity/Activity.tsx
> +            Alert.alert('Error', 'Please select Start and End date.');
this needs localization

2024-09-10 19:04 UTC, kaloudis commented on babel.config.js
> +    ]
I am curious about this too

2024-09-23 17:46 UTC, kaloudis commented
closing in favor of https://github.com/ZeusLN/zeus/pull/2436

2024-09-23 17:46 UTC, closed without merging