LSPS1: Change token to discount code
ZeusLN/zeus pull request #2275
Opened 2024-07-02 14:03 UTC by shubhamkmr04

2024-07-08 19:47 UTC, kaloudis commented
Since we're rewriting the string entirely, let's rename it. Let's also delete `views.Settings.LSP.lspAccessKey` if it's not longer being used so translators don't have to translate it

2024-07-08 19:47 UTC, kaloudis requested changes

2024-07-08 19:47 UTC, kaloudis commented on locales/en.json
> +    "views.LSPS1.token": "Discount code",
Since we're rewriting the string entirely, let's rename it - maybe `general.discountCode`. Let's also delete `views.Settings.LSP.lspAccessKey` if it's not longer being used so translators don't have to translate it

2024-07-09 08:26 UTC, shubhamkmr04 commented on locales/en.json
> +    "views.LSPS1.token": "Discount code",
Sure

2024-07-09 13:59 UTC, kaloudis approved these changes

2024-07-09 13:59 UTC, merged