Add ContactStore
ZeusLN/zeus pull request #2283
Opened 2024-07-10 14:03 UTC by shubhamkmr04

2024-07-10 14:46 UTC, kaloudis commented
Somewhat on the right track, but the initial loading of contacts should happen when the wallet loads up. We don't want to read from encrypted storage every time we go to contact details, we just want to read from the store

2024-08-15 02:42 UTC, kaloudis commented on stores/ContactStore.ts
> +                console.log('heree', this.prefillContact);
remove this

2024-08-15 02:43 UTC, kaloudis requested changes
change requested

2024-08-15 02:52 UTC, shubhamkmr04 commented on stores/ContactStore.ts
> +                console.log('heree', this.prefillContact);
done

2024-08-28 02:27 UTC, kaloudis requested changes

2024-08-28 02:27 UTC, kaloudis commented on views/Settings/Contacts.tsx
> +                    {ContactStore?.loading ? (
since loading is used twice (here and 405), let's destructure it on line 206

2024-08-28 02:28 UTC, kaloudis requested changes

2024-08-28 02:28 UTC, kaloudis commented on views/ContactDetails.tsx
> +                                        ContactStore.setPrefillContact(
since `setPrefillContact` is used twice (here and 242), let's destructure it at the top of the render function

2024-08-28 16:00 UTC, kaloudis approved these changes

2024-08-28 16:01 UTC, merged