Display Notes on Activity view
ZeusLN/zeus pull request #2292
Opened 2024-07-18 16:18 UTC by shubhamkmr04

2024-08-27 15:48 UTC, kaloudis requested changes
![Simulator Screenshot - iPhone 15 Plus - 2024-08-27 at 11 47 31](https://github.com/user-attachments/assets/d0df637d-021b-4cb0-9443-a402b8e7d3a4)

I think we should have a max char limit on the display preview here.

Note label is also rendered oddly here.

2024-09-03 11:32 UTC, shubhamkmr04 commented
> ![Simulator Screenshot - iPhone 15 Plus - 2024-08-27 at 11 47 31](https://private-user-images.githubusercontent.com/1878621/361882287-d0df637d-021b-4cb0-9443-a402b8e7d3a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTE3MzMsIm5iZiI6MTcyNTM1MTQzMywicGF0aCI6Ii8xODc4NjIxLzM2MTg4MjI4Ny1kMGRmNjM3ZC0wMjFiLTRjYjAtOTQ0My1hNDAyYjhlN2QzYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDNUMDgxNzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRhNDNkNzRkMDZiZDA3NzI4OWQ0OWYxMDczYWEwMWE5NDQ2YjgzYmRlYjM3ZDJkN2ZlMTFkOGQ5MGY0YjI0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.imdQxXCo29tayA0OXv6-mfcS9F5rVVsznxmKfhyX0G4)
> 
> I think we should have a max char limit on the display preview here.
> 
> Note label is also rendered oddly here.

![Simulator Screenshot - iPhone 15 Pro - 2024-09-03 at 17 00 45](https://github.com/user-attachments/assets/3aff11c1-dbbd-44cd-b206-6eb9ef1cd928)

Fixed the notes overlapping and the char limit to 150, you think it would work ?

2024-09-04 17:19 UTC, kaloudis commented
Looking good now, visually.

![simulator_screenshot_C304922D-BC84-4C9D-92EC-6700979F63C0](https://github.com/user-attachments/assets/89f9769e-a249-4358-abc5-4127cc1f8150)

2024-09-04 17:24 UTC, kaloudis requested changes

2024-09-04 17:24 UTC, kaloudis commented on views/Wallet/Wallet.tsx
> +        NotesStore?.loadNoteKeys();
I don't believe we need to load this every time we hit the wallet screen. On `connecting` should suffice

2024-09-04 17:24 UTC, kaloudis commented on views/Activity/Activity.tsx
> +            const strippedNoteKeys = NotesStore.noteKeys.map((key) =>
going through this map and creating this object for every item in activity is both inefficient and redundant. If we need this index of stripped keys we should do it once. Perhaps in `loadNoteKeys`?

2024-09-04 17:25 UTC, kaloudis commented
We need to rebase this too, once ready. Please rewind your commits and rebase instead of doing a merge commit, please.

2024-09-05 16:43 UTC, shubhamkmr04 commented on views/Wallet/Wallet.tsx
> +        NotesStore?.loadNoteKeys();
Yup, we have covered that in [2393](https://github.com/ZeusLN/zeus/pull/2393)

2024-09-10 18:43 UTC, kaloudis commented on views/AddNotes.tsx
> +            const key: any = payment_hash || txid || getRPreimage;
same here

2024-09-10 18:44 UTC, kaloudis commented on views/AddNotes.tsx
> +                                    payment_hash || txid || getRPreimage;
same here. I do not understand the changes to this file

2024-09-10 18:45 UTC, kaloudis commented on views/Invoice.tsx
> +                        getRPreimage: getNoteKey
I really dislike the name of the prop we're passing in here. Doesn't it work better as `noteKey` or something akin to that?

2024-09-10 18:46 UTC, kaloudis commented on views/Payment.tsx
> +                        payment_hash: getNoteKey
same here with the prop name here. do we handle these differently?

nit: also confused by the different casing

2024-09-11 09:08 UTC, shubhamkmr04 commented on views/AddNotes.tsx
> +            this.state.getRPreimage;
we were getting type error here like `Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.` once I removed **here-** because it was already coming in getNoteKey

2024-09-16 11:16 UTC, kaloudis approved these changes
tACK

2024-09-16 11:16 UTC, merged