Link remote Pubkey from Channel view to the stored contacts
ZeusLN/zeus pull request #2299
Opened 2024-07-24 09:04 UTC by shubhamkmr04

https://github.com/ZeusLN/zeus/issues/2082

2024-07-24 14:17 UTC, kaloudis commented
Can you please add a description of the change and some screenshots or video illustrating the change?

2024-07-24 15:13 UTC, shubhamkmr04 commented
> Can you please add a description of the change and some screenshots or video illustrating the change?

added a description and demo video

2024-08-26 18:35 UTC, kaloudis requested changes

2024-08-26 18:35 UTC, kaloudis commented on views/Channels/Channel.tsx
> +                        <Text
I really like the display component here but i don't think we need the label. Let's remove `Matching Contact Found`

2024-08-27 05:24 UTC, shubhamkmr04 commented on views/Channels/Channel.tsx
> +                        <Text
sure

2024-08-27 13:56 UTC, kaloudis requested changes

2024-08-27 13:56 UTC, kaloudis commented on locales/en.json
> +    "views.Channel.matchingContactFound": "Matching Contact Found",
we're no longer using this locale now

2024-08-28 02:18 UTC, kaloudis commented
Initial tests look good. We're gonna have to refactor this with the `ChannelsStore` changes though. We'll try to get that in soon.

2024-08-28 16:01 UTC, kaloudis requested changes

2024-08-28 16:01 UTC, kaloudis commented on views/Channels/Channel.tsx
> +    loadContacts = async () => {
Please rebase and refactor to use the newly added `ContactStore`

2024-08-29 14:32 UTC, kaloudis commented on views/Channels/Channel.tsx
> +        loadContacts();
Why do we have to load contacts again on page load? Aren't they accessible in the store already?

2024-08-29 15:18 UTC, shubhamkmr04 commented on views/Channels/Channel.tsx
> +        loadContacts();
yeahh. you're right. I'll change that

2024-08-30 17:41 UTC, kaloudis approved these changes
tACK

2024-08-30 17:41 UTC, merged