Inbound routing fees
ZeusLN/zeus pull request #2354
Opened 2024-08-13 11:33 UTC by shubhamkmr04

# Description

Relates to issue: [**ZEUS-2185**](https://github.com/ZeusLN/zeus/issues/2185)

_We want to implement the ability to set the inbound routing fees_

This pull request is categorized as a:

- [X] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance
- [ ] Other

## Checklist
- [X] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [X] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [X] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [X] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [X] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [ ] Android
- [X] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] Embedded LND
- [X] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (CLNRest)
- [ ] LndHub
- [ ] [DEPRECATED] Core Lightning (c-lightning-REST)
- [ ] [DEPRECATED] Core Lightning (Spark)
- [ ] [DEPRECATED] Eclair

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the ZEUS [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

2024-08-13 11:36 UTC, shubhamkmr04 commented
![Simulator Screenshot - iPhone 15 Pro - 2024-08-13 at 17 04 08](https://github.com/user-attachments/assets/02eabdbd-4560-4ad0-8033-46e14529f9d2)

2024-09-18 17:19 UTC, kaloudis commented on components/SetFeesForm.tsx
> +                            )} Inbound (${localeString('general.sats')})`}
`Inbound` needs to be localized

2024-09-18 17:19 UTC, kaloudis commented on components/SetFeesForm.tsx
> +                            )} Inbound (${localeString('general.percentage')})`}
`Inbound` needs to be localized

2024-09-19 16:02 UTC, kaloudis commented on models/ChannelInfo.ts
> +    inbound_fee_rate_milli_msat: string;
let's add `?` to these two new fields as older nodes may not have them

2024-09-19 16:03 UTC, kaloudis commented on views/Routing/SetFees.tsx
> +                                }`}
for these two, let's check to see if they exist or return `null` - otherwise there will be cases here where it returns `NaN`

2024-09-19 16:04 UTC, kaloudis requested changes

2024-09-19 16:04 UTC, kaloudis commented on components/FeeBreakdown.tsx
> +                        />
these two should only be displayed if `supportInboundFees`

2024-09-19 16:21 UTC, shubhamkmr04 commented on views/Routing/SetFees.tsx
> +                                }`}
would it be better to return `0` instead of `null` ?

2024-09-19 19:34 UTC, kaloudis commented on views/Routing/SetFees.tsx
> +                                }`}
No

2024-09-19 19:35 UTC, kaloudis commented on views/Routing/SetFees.tsx
> +                                }`}
`undefined` would be best

2024-09-20 11:25 UTC, shubhamkmr04 commented on backends/LND.ts
> +                }),
did the changes!

2024-09-20 16:21 UTC, kaloudis approved these changes
uTACK

2024-09-20 16:21 UTC, merged