Add modal to dismiss custodial wallet warning
ZeusLN/zeus pull request #2394
Opened 2024-09-05 15:25 UTC by shubhamkmr04

Relates to issue: **[ZEUS-2344](https://github.com/ZeusLN/zeus/issues/2344)**

We have added a modal which will dismiss the custodial wallet warning

This pull request is categorized as a:

- [ ] New feature
- [ ] Bug fix
- [ ] Code refactor
- [X] Configuration change
- [ ] Locales update
- [ ] Quality assurance
- [ ] Other

## Checklist
- [X] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [X] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [X] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [X] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [X] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [ ] Android
- [X] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] Embedded LND
- [ ] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (CLNRest)
- [X] LndHub
- [ ] [DEPRECATED] Core Lightning (c-lightning-REST)
- [ ] [DEPRECATED] Core Lightning (Spark)
- [ ] [DEPRECATED] Eclair

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the ZEUS [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

2024-09-05 15:28 UTC, shubhamkmr04 commented
https://github.com/user-attachments/assets/12d81b1e-9568-419f-9d7a-cbf919a332eb

Demo video just for the UI update

2024-09-06 19:22 UTC, kaloudis commented
After you hit 'Dismiss warning' it should kick you out to the main wallet view

2024-09-10 18:38 UTC, kaloudis commented on stores/SettingsStore.ts
> +    };
as it stands now, this will not persist across restarts of the app. this needs to be saved to local storage on per node/account basis

2024-09-10 18:39 UTC, kaloudis requested changes

2024-09-10 18:39 UTC, kaloudis commented on stores/SettingsStore.ts
> +    };
as it stands now, this will not persist across restarts of the app. this needs to be saved to local storage on per node/account basis

2024-09-14 08:00 UTC, kaloudis requested changes

2024-09-14 08:00 UTC, kaloudis commented on views/Settings/CustodialWalletWarning.tsx
> +                                "I'm not just lying to get this over with"
these need to be localized

2024-09-14 08:01 UTC, kaloudis commented on views/Settings/CustodialWalletWarning.tsx
> +                                    title="CLOSE"
this needs to be localized

2024-09-14 08:01 UTC, kaloudis commented on views/Settings/CustodialWalletWarning.tsx
> +    closeButton: {
is this used?

2024-09-14 12:51 UTC, shubhamkmr04 commented on views/Settings/CustodialWalletWarning.tsx
> +    closeButton: {
nope, removed it

2024-09-15 11:30 UTC, kaloudis requested changes

2024-09-15 11:30 UTC, kaloudis commented on views/Settings/CustodialWalletWarning.tsx
> +                                warning:
this needs to be localized

2024-09-16 10:55 UTC, kaloudis approved these changes
tACK

2024-09-16 10:56 UTC, merged