improved UX and error handling for wallet configuration
ZeusLN/zeus pull request #2594
Opened 2024-12-02 18:15 UTC by myxmaster

# Description

This fixes #2172  (all of it, so issue=PR description).

Additionally fixed `onFocus` and added `onBlur` for `TextInput` component.

This pull request is categorized as a:

- [x] New feature
- [x] Bug fix
- [x] Code refactor
- [ ] Configuration change
- [x] Locales update
- [ ] Quality assurance
- [ ] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [x] Yes
- [ ] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [x] Embedded LND
- [x] LND (REST)
- [x] LND (Lightning Node Connect)
- [x] Core Lightning (CLNRest)
- [x] LndHub
- [x] [DEPRECATED] Core Lightning (c-lightning-REST)
- [x] [DEPRECATED] Core Lightning (Spark)
- [x] [DEPRECATED] Eclair

### Locales
- [x] I’ve added new locale text that requires translations
- [x] I’m aware that new translations should be made on the ZEUS [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

2024-12-19 15:51 UTC, kaloudis requested changes

2024-12-19 15:51 UTC, kaloudis commented on views/Settings/WalletConfiguration.tsx
> +                                            /^[a-zA-Z0-9-.:]+$/;
this is incorrect. this doesn't allow you to input forward slashes, so you can't even specify https VS http

We should break this off into a utility func with accompanying tests

2024-12-19 15:52 UTC, kaloudis commented on views/Settings/WalletConfiguration.tsx
> +                                                    !/^[a-zA-Z0-9-.]+(:\d+)?$/.test(
this one as well

2024-12-19 15:52 UTC, kaloudis commented on views/Settings/WalletConfiguration.tsx
> +                                                            /[^a-zA-Z0-9-.:]/g,
any func w regex needs to be broken into a utility func and tests added

2025-01-03 06:17 UTC, vpati85 commented
I have a wallet at Pontem
When my wallet was created, 
It have multiple Wallet in one wallet 
I transfer fund APT  account2 to account 2.
Both the wallets were connected together but after I transferred the amount from one wallet to another, I am not able to access the transferred amount again. 
 after trying connect by clicking repeatedly, I am not able to access account2 and withdraw it.
After copying the seed phrase  put in pontem
In other phone  in pontem wallet , i was entered same phrase but account1 is recovered but account2 is not recover and not connected with account 1.
I am trying again to recover  account 2  in another phone.
Account 1   "0xa86......3127" (my original wallet, access properly)
Account 2 "0x08b......e2d0" (apt fund, i want to recover to access apt coin, not accessible)
Both wallet connect each other in pontem app
But "0xa86 ..3127" is easily accessible 
But "0x086.....e2d0" that wallet have fund, not accessible 

Account 1
0xa86f402ffc4eaa8581fc5a14f1ce5cff9c35d21f01be27f35766fca7fd383127
Account 2
0x08bd2ca56cd0fd4ad975895fd3bd17a215b12e246ac25e6ad6f522678c57e2d0

Now what i do 
Please help 
My telegram @vpati5189
my email vpati5185@gmail.com

2025-01-03 06:17 UTC, vpati85 commented
I have a wallet at Pontem
When my wallet was created, 
It have multiple Wallet in one wallet 
I transfer fund APT  account2 to account 2.
Both the wallets were connected together but after I transferred the amount from one wallet to another, I am not able to access the transferred amount again. 
 after trying connect by clicking repeatedly, I am not able to access account2 and withdraw it.
After copying the seed phrase  put in pontem
In other phone  in pontem wallet , i was entered same phrase but account1 is recovered but account2 is not recover and not connected with account 1.
I am trying again to recover  account 2  in another phone.
Account 1   "0xa86......3127" (my original wallet, access properly)
Account 2 "0x08b......e2d0" (apt fund, i want to recover to access apt coin, not accessible)
Both wallet connect each other in pontem app
But "0xa86 ..3127" is easily accessible 
But "0x086.....e2d0" that wallet have fund, not accessible 

Account 1
0xa86f402ffc4eaa8581fc5a14f1ce5cff9c35d21f01be27f35766fca7fd383127
Account 2
0x08bd2ca56cd0fd4ad975895fd3bd17a215b12e246ac25e6ad6f522678c57e2d0

Now what i do 
Please help 
My telegram @vpati5189
my email vpati5185@gmail.com

2025-01-03 06:17 UTC, vpati85 commented on views/Settings/WalletConfiguration.tsx
> +                                                            /[^a-zA-Z0-9-.:]/g,
I have a wallet at Pontem
When my wallet was created, 
It have multiple Wallet in one wallet 
I transfer fund APT  account2 to account 2.
Both the wallets were connected together but after I transferred the amount from one wallet to another, I am not able to access the transferred amount again. 
 after trying connect by clicking repeatedly, I am not able to access account2 and withdraw it.
After copying the seed phrase  put in pontem
In other phone  in pontem wallet , i was entered same phrase but account1 is recovered but account2 is not recover and not connected with account 1.
I am trying again to recover  account 2  in another phone.
Account 1   "0xa86......3127" (my original wallet, access properly)
Account 2 "0x08b......e2d0" (apt fund, i want to recover to access apt coin, not accessible)
Both wallet connect each other in pontem app
But "0xa86 ..3127" is easily accessible 
But "0x086.....e2d0" that wallet have fund, not accessible 

Account 1
0xa86f402ffc4eaa8581fc5a14f1ce5cff9c35d21f01be27f35766fca7fd383127
Account 2
0x08bd2ca56cd0fd4ad975895fd3bd17a215b12e246ac25e6ad6f522678c57e2d0

Now what i do 
Please help 
My telegram @vpati5189
my email vpati5185@gmail.com

2025-01-31 17:09 UTC, kaloudis commented
> Actually, I think we should change the GUI label from `Host` into `Server address`. -> Technically, what we allow users to enter here, is not always a valid host, domain or URL.
> 
>     * A hostname never contains protocol (http/https) or path (exampe.com/any/path/).
> 
>     * A domain never contains subdomains (subdomain.domain.com) and an IP address is not a domain either.
> 
>     * A Web-URL always contains protocol, but we allow `your-server.com` as well
> 
> 
> @kaloudis If you agree, I will change all labels and rename the ValidationUtils methods accordingly (e.g. `isValidHostname` -> `isValidServerAddress`).

I can get behind this.

I also want to potentially but the Port line right below it, instead of the macaroon. We ended up swapping them because of an issue where the keyboard would be covering it. Not sure if we've remedied that yet. LMK what you find.

2025-02-03 07:59 UTC, shubhamkmr04 commented
> I think all issues we talked about are now fixed. Just that error message layout problem is still there, I'll care about that in another PR.

Sounds good. Looking much better now

2025-02-05 10:37 UTC, shubhamkmr04 reviewed
maybe we shouldn't allow plain strings (for ex. `localhost`) in server address ?(keeping save wallet btn inactive in that case)

2025-02-05 13:31 UTC, kaloudis commented
We need to keep the plain string option for people who have custom DNS set up and access their nodes via private VPNs

2025-02-05 13:56 UTC, shubhamkmr04 reviewed
tACK

2025-02-05 17:28 UTC, kaloudis approved these changes

2025-02-05 17:29 UTC, merged