Payments: Update `getPayments` call to limit the number of payments
ZeusLN/zeus pull request #2614
Opened 2024-12-10 17:43 UTC by shubhamkmr04

2024-12-10 17:45 UTC, kaloudis commented on backends/LightningNodeConnect.ts
> +                max_payment: data && data?.maxPayments
`max_payments` plural?

2024-12-10 17:52 UTC, shubhamkmr04 commented on backends/LightningNodeConnect.ts
> +                max_payment: data && data?.maxPayments
tested it on only LND yet.
making it a draft PR. gonna work on other interfaces as well

2024-12-11 16:19 UTC, kaloudis commented on stores/PaymentsStore.ts
> +        maxPayments: any = undefined,
I believe this should be of type `number`

2024-12-14 02:07 UTC, kaloudis requested changes

2024-12-14 02:07 UTC, kaloudis commented on stores/PaymentsStore.ts
> +    public getPayments = async (maxPayments?: number, reversed?: boolean) => {
let's pass in the params as a single object so it's easier to pass in just one or the other

2024-12-14 20:37 UTC, kaloudis commented
@shubhamkmr04 did you want to make any more changes here or is this ready for testing and review?

2024-12-15 06:18 UTC, shubhamkmr04 commented
> @shubhamkmr04 did you want to make any more changes here or is this ready for testing and review?

Its good to go i think

2024-12-16 19:17 UTC, kaloudis requested changes
Tested. Everything looks good but we need to change `backends/EmbeddedLND` as well

2024-12-19 15:58 UTC, kaloudis approved these changes
tACK

2024-12-19 16:00 UTC, merged