Enhance on-chain receive workflow and address type selection
ZeusLN/zeus pull request #2624
Opened 2024-12-12 12:34 UTC by myxmaster

# Description

These changes
- improve rendering performance, when clicking `Receive` in on-chain swipeable row
  - moved selectedIndex initialization to constructor (no more renderings with wrong selectedIndex)
  - added `selectedIndex !== 2` condition to prevent unnecessary rendering
- show SettingsButton instead of ClearButton for selectedIndex=2 (on-chain), because here it makes sense to choose address type (and not going back to create another invoice)
- enhance addressType modalBox (Receive and InvoiceSettings)
  - ~~60% height~~
  - scrollable content for longer translations
  - prevents unnecessary updates when same address type is selected
  - Receive only: automatically generates new on-chain address when new address type is picked

This pull request is categorized as a:

- [ ] New feature
- [ ] Bug fix
- [x] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance
- [ ] Other

## Checklist
- [ ] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] Embedded LND
- [x] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (CLNRest)
- [ ] LndHub
- [ ] [DEPRECATED] Core Lightning (c-lightning-REST)
- [ ] [DEPRECATED] Core Lightning (Spark)
- [ ] [DEPRECATED] Eclair

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the ZEUS [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `yarn` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

2024-12-17 04:57 UTC, kaloudis requested changes
there's a bug. Go to Receive. Select an address type. Autogenerate triggers but no invoice or QR is displayed

2024-12-19 02:13 UTC, kaloudis commented on views/Settings/InvoicesSettings.tsx
> +                        height: windowSize.height * 0.6,
not sure I like this

2024-12-19 15:36 UTC, kaloudis requested changes

2024-12-19 15:36 UTC, kaloudis commented on views/Receive.tsx
> +                          selectedIndex !== 2 ? (
we need to redo the logic here.

If a node doesn't support address type selection, it should still show the X here. Otherwise it is not uniform.

`haveInvoice && !(selectedIndex === 2 && BackendUtils.supportsAddressTypeSelection())` should do it

2024-12-22 19:13 UTC, kaloudis requested changes
There's another bug here:

When creating a new address from an external account, users are still allowed to change the address type, even though external accounts have fixed address types.

To make matters worse, the newly generated addresses come from the internal on-chain wallet but the label above the QR persists with the external account label.

2025-01-02 11:29 UTC, shubhamkmr04 reviewed
LGTM

2025-01-05 18:17 UTC, kaloudis requested changes

2025-01-05 18:17 UTC, kaloudis commented on views/Receive.tsx
> +            enableLSP: settings?.enableLSP || true,
This will cause the LSP to always be enabled

2025-01-06 15:58 UTC, kaloudis approved these changes
tACK

2025-01-06 15:58 UTC, merged