Use index for keyExtractor in nodes DragList
ZeusLN/zeus pull request #2647
Opened 2024-12-17 23:03 UTC by myxmaster

# Description

Rare edge case, but previously, nodes with identical configurations had the same id, leading to
`ERROR  Warning: Encountered two children with the same key` (and whatever issues in the future).

Now also using index for keyExtractor in nodes DragList.
Since that broke drag functionality, updated DragList to 3.8.0 -> now working fine.
Dragging also tested in currency converter with new DragList version -> working fine as well.

This pull request is categorized as a:

- [ ] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Quality assurance
- [x] Other

## Checklist
- [x] I’ve run `yarn run tsc` and made sure my code compiles correctly
- [x] I’ve run `yarn run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `yarn run prettier` and made sure my code is formatted correctly
- [x] I’ve run `yarn run test` and made sure all of the tests pass

## Testing

If you modified or added a utility file, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [x] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [x] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [ ] Embedded LND
- [x] LND (REST)
- [ ] LND (Lightning Node Connect)
- [ ] Core Lightning (CLNRest)
- [ ] LndHub
- [ ] [DEPRECATED] Core Lightning (c-lightning-REST)
- [ ] [DEPRECATED] Core Lightning (Spark)
- [ ] [DEPRECATED] Eclair

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the ZEUS [Transfix page](https://app.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [x] Contributors will need to run `yarn` after this PR is merged in
- [x] 3rd party dependencies have been modified:
    * verify that `package.json` and `yarn.lock` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

2024-12-18 14:02 UTC, shubhamkmr04 reviewed
tACK

2024-12-18 15:48 UTC, kaloudis requested changes

2024-12-18 15:48 UTC, kaloudis commented on views/Settings/Wallets.tsx
> +                            keyExtractor={(item: Node) => {
you don't have to add all this to address this react issue. You can simply, use the second param here, `index` and append it to the string you return for the key

2024-12-19 14:32 UTC, kaloudis approved these changes

2024-12-19 14:32 UTC, merged