Tor works
ZeusLN/zeus pull request #394
Opened 2020-12-02 18:09 UTC by gabidi

# Description
WIP - Do not review yet, place holder for final testing on both platforms.

- Embeds Tor Daemon + Onion Routing into Zeus, removing the dependency on Orbot and allowing Tor usage on IOS
- Updates backend APIs to use Tor when enabled

Relates to issue: **ZEUS-166**
Claims iOS + Android Tor Bounty:
https://github.com/ZeusLN/zeus/blob/master/docs/Bounties.md#tor-on-android
https://github.com/ZeusLN/zeus/blob/master/docs/Bounties.md#tor-on-ios

_Please enter a description and screenshots, if appropriate, of the work covered in this PR_

This pull request is categorized as a:

- [ x] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Other

## Checklist
- [ ] I’ve run `npm run tsc` and make sure my code didn’t produce errors 
- [ ] I’ve run `npm run prettier` and formatted my code correctly

## Testing

If you added new functionality or fixed a bug, did you add new unit tests?

- [ ] No, I’m a fool
- [ ] Yes
- [ ] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [ ] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [x ] LND
- [x] c-lightning-REST
- [ ] spark
- [x] Eclair
- [ ] LndHub

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the Zeus [Transfix page](https://www.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [x ] Contributors will need to run `npm install` after this PR is merged in
- [x] 3rd party dependencies have been modified:
    * verify that `package.json` and `package-lock.json` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [x] Changes were made that require an update to onboarding

2020-12-02 23:07 UTC, AliMeer commented
Looks great so far 👍
Where are tor daemon settings configured?

2020-12-09 17:55 UTC, ZeusLN commented
`enableTor` should be found on lines 188, 203, 257 (roughly) of `AddEditNode.tsx` to ensure the property is loaded properly on the edit node screen

2020-12-09 18:13 UTC, MONIMAKER365 approved these changes

2020-12-09 18:16 UTC, MONIMAKER365 approved these changes

2020-12-12 18:04 UTC, kaloudis requested changes

2020-12-12 18:04 UTC, kaloudis commented on package.json
> +    "react-native-tor": "github:Sifir-io/react-native-tor",
Can you lock in the version here now that the package is public?

2020-12-13 10:09 UTC, MONIMAKER365 requested changes

2020-12-13 10:09 UTC, MONIMAKER365 commented on .eslintrc.js
> -  radix: 'as-needed',
`  comma-dangle: 0,`
  radix: 'as-needed',

2020-12-13 10:09 UTC, MONIMAKER365 submitted a review, later dismissed

2020-12-13 16:03 UTC, gabidi commented on package.json
> +    "react-native-tor": "github:Sifir-io/react-native-tor",
locked to npm version 0.1.0

2020-12-17 02:45 UTC, kaloudis commented
Looks good to merge if you tackle https://github.com/ZeusLN/zeus/pull/394#issuecomment-741945580

2020-12-17 10:42 UTC, gabidi commented
> Looks good to merge if you tackle [#394 (comment)](https://github.com/ZeusLN/zeus/pull/394#issuecomment-741945580)

Didn't see that one before. Not sure what it means but will check and let you know.

2020-12-22 06:05 UTC, MONIMAKER365 approved these changes

2020-12-22 06:06 UTC, MONIMAKER365 approved these changes

2020-12-22 06:07 UTC, MONIMAKER365 submitted a review, later dismissed

2020-12-24 02:28 UTC, MONIMAKER365 approved these changes

2020-12-24 02:29 UTC, MONIMAKER365 approved these changes
approved

2021-01-18 21:13 UTC, kaloudis submitted a review, later dismissed

2021-01-24 21:54 UTC, merged