SignMessage updated and added CL & Eclair backends
ZeusLN/zeus pull request #504
Opened 2021-07-28 20:13 UTC by pseudozach

# Description

Relates to issue: https://github.com/ZeusLN/zeus/pull/500#issuecomment-887765899

This PR resolves lnurl-auth specification compliance issue when Zeus uses LND v2 signmessage as mentioned in above comment. It also adds support for other backends.

This pull request is categorized as a:

- [ ] New feature
- [ ] Bug fix
- [X] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Other

## Checklist
- [X] I’ve run `npm run tsc` and make sure my code didn’t produce errors 
- [X] I’ve run `npm run prettier` and formatted my code correctly

## Testing

If you added new functionality or fixed a bug, did you add new unit tests?

- [X] No, I’m a fool
- [ ] Yes
- [ ] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [X] Android
- [ ] iOS

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [X] LND
- [X] c-lightning-REST
- [ ] spark
- [X] Eclair
- [ ] LndHub

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the Zeus [Transfix page](https://www.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `npm install` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `package-lock.json` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

2021-07-29 01:03 UTC, kaloudis commented on backends/CLightningREST.ts
> +    signMessage = (message: any) =>
turn this to `message: string`

2021-07-29 01:03 UTC, kaloudis commented on backends/CLightningREST.ts
> +            message: `${message}`
this can just be `message`

2021-07-29 01:03 UTC, kaloudis commented on backends/Eclair.ts
> +    signMessage = (message: any) =>
`message: string`

2021-07-29 01:03 UTC, kaloudis commented on backends/Eclair.ts
> +            msg: `${message}`
`msg: message`

2021-07-29 01:03 UTC, kaloudis commented on backends/LND.ts
> +    signMessage = (message: any) =>
`message: string`

2021-07-29 01:04 UTC, kaloudis commented on backends/LND.ts
> +            msg: `${message}`
`msg: message`

2021-07-29 03:50 UTC, pseudozach commented on backends/CLightningREST.ts
> +    signMessage = (message: any) =>
Sorry I was just going with what was above in similar code. I'll change all of them to regular variable.

2021-07-29 03:57 UTC, pseudozach commented on backends/CLightningREST.ts
> +            message: `${message}`
I'll change all of them to regular variable.

2021-07-29 19:50 UTC, hsjoberg requested changes

2021-07-29 19:50 UTC, hsjoberg commented on backends/CLightningREST.ts
> +            message: message
Is `message` here base64 encoded?

According to the API docs, it should be encoded in base64 when using the REST API:
https://api.lightning.community/#v1-signmessage

Also small nit depedning on how you do code style in the project: message could use the shorthand syntax: `{ message }`.

2021-07-29 19:51 UTC, hsjoberg requested changes

2021-07-29 19:51 UTC, hsjoberg commented on backends/LND.ts
> +            msg: message
Is message here base64 encoded?

According to the lnd's API docs, it should be encoded in base64 when using the REST API:
https://api.lightning.community/#v1-signmessage

2021-07-29 23:22 UTC, pseudozach commented on backends/LND.ts
> +            msg: message
yes, the string is passed through the function below which encodes base64 and then sent to the API endpoints.
>Base64Utils.btoa(text)

2021-08-11 03:39 UTC, kaloudis commented
Can we create a new function in the backends called `supportsMessageSigning`?

2021-08-11 04:39 UTC, pseudozach commented
> Can we create a new function in the backends called `supportsMessageSigning`?

done please check

2021-08-11 04:40 UTC, kaloudis commented on stores/MessageSignStore.ts
> +        console.log("text, body ", text, body);
console log

2021-08-11 04:40 UTC, kaloudis commented on android/build.gradle
> +        minSdkVersion = 25
why the sdkVersion change?

2021-08-11 04:41 UTC, kaloudis commented on android/app/src/main/AndroidManifest.xml
> +    <uses-sdk tools:overrideLibrary="com.sifir.tor"/>
are these changes required?

2021-08-11 04:44 UTC, kaloudis approved these changes

2021-08-11 05:08 UTC, merged