Added error icon for failed fetching of fee rates
ZeusLN/zeus pull request #574
Opened 2021-09-01 08:20 UTC by shubhamkmr04

2021-09-01 08:25 UTC, shubhamkmr04 commented
@kaloudis please check this out.

2021-09-01 15:26 UTC, kaloudis commented on images/SVG/Error Circle.svg
> +<circle cx="60" cy="60" r="56" stroke="#E14C4C" stroke-width="8"/>
We should be able to merge these two SVGs: take this line and put it on line two of the other file

2021-09-01 15:26 UTC, kaloudis commented
Looks good. Let's just try to make it a single SVG

2021-11-06 22:45 UTC, kaloudis commented
@Bosch-0 do we have a combined icon for this yet?

2021-11-09 02:42 UTC, Bosch-0 commented
Should be able to export the icon from here: https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/Zeus?node-id=3623%3A18354

Will DM you the SVG export too if that's easier than going into Figma

2021-12-28 15:02 UTC, shubhamkmr04 commented
Just fixed error icon by using only one svg file.

2021-12-28 16:16 UTC, shubhamkmr04 commented
@kaloudis please checkout if the PR is ready to merge.

2022-01-06 05:53 UTC, kaloudis requested changes

2022-01-06 05:53 UTC, kaloudis commented on images/SVG/Error Cross.svg
> +</svg>
this file can be deleted now

2022-01-06 05:53 UTC, kaloudis commented on images/SVG/Error Circle.svg
> +<circle cx="60" cy="60" r="56" stroke="#E14C4C" stroke-width="8"/>
this file can be deleted now

2022-01-06 05:53 UTC, kaloudis commented on views/EditFee.tsx
> +                            </View>
Try to remove the surrounding `<View>` tag from this - I don't think it's necessary

2022-01-06 09:20 UTC, shubhamkmr04 commented
@kaloudis Done!

2022-01-06 16:26 UTC, kaloudis approved these changes

2022-01-07 21:37 UTC, merged