Account for msats in LND routing fees
ZeusLN/zeus pull request #780
Opened 2022-02-07 23:17 UTC by deregs

# Description

Relates to issue: **[569](https://github.com/ZeusLN/zeus/issues/569)**

Only showing decimal places if there are msats involved in the fee:
![Screen Shot 2022-02-07 at 6 12 40 PM](https://user-images.githubusercontent.com/93104057/152887933-70fa3b15-607e-499d-9fa2-0292141dae13.png)

This pull request is categorized as a:

- [x] New feature
- [ ] Bug fix
- [ ] Code refactor
- [ ] Configuration change
- [ ] Locales update
- [ ] Other

## Checklist
- [x] I’ve run `npm run tsc` and made sure my code compiles correctly
- [x] I’ve run `npm run lint` and made sure my code didn’t contain any problematic patterns
- [x] I’ve run `npm run prettier` and made sure my code is formatted correctly
- [x] I’ve run `npm run test` and made sure all of the tests pass

## Testing

If you added new functionality or fixed a bug, did you add new unit tests?

- [x] No, I’m a fool
- [ ] Yes
- [ ] N/A

I have tested this PR on the following platforms (please specify OS version and phone model/VM):

- [ ] Android
- [x] iOS 13.7 on iPhone 11 Pro

I have tested this PR with the following types of nodes (please specify node version and API version where appropriate):

- [x] LND
- [ ] c-lightning-REST
- [ ] spark
- [ ] Eclair
- [ ] LndHub

### Locales
- [ ] I’ve added new locale text that requires translations
- [ ] I’m aware that new translations should be made on the Zeus [Transfix page](https://www.transifex.com/ZeusLN/zeus/) and not directly to this repo

### Third Party Dependencies and Packages

- [ ] Contributors will need to run `npm install` after this PR is merged in
- [ ] 3rd party dependencies have been modified:
    * verify that `package.json` and `package-lock.json` have been properly updated
    * verify that dependencies are installed for both iOS and Android platforms

### Other:

- [ ] Changes were made that require an update to the README
- [ ] Changes were made that require an update to onboarding

2022-02-07 23:26 UTC, kaloudis commented on stores/UnitsStore.ts
> +        const sats = Math.round(Number(value) * 1000) / 1000;
Might be time to bring in BigNumber https://mikemcl.github.io/bignumber.js/

2022-02-08 02:48 UTC, deregs commented on stores/UnitsStore.ts
> +        const sats = Math.round(Number(value) * 1000) / 1000;
Cool, added BigNumber in FeeStore to prevent the rounding errors

2022-03-04 22:42 UTC, kaloudis requested changes

2022-03-04 22:42 UTC, kaloudis commented on package.json
> +    "bignumber.js": "^9.0.2",
please lock the version number here by removing the caret. Also make sure `package-lock.json` gets committed

2022-03-05 03:48 UTC, kaloudis commented
haha you got a rebase from hell. check the diff.

2022-03-05 04:02 UTC, deregs commented
> haha you got a rebase from hell. check the diff.

Yeah lol I messed up bad on that rebase so just opened a fresh PR

2022-03-05 04:02 UTC, closed without merging